# Generated by Django 2.1 on 2019-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20190206_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.URLField(default='#', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default='#', max_length=250),
        ),
    ]
